### ISSUE TITLE
On runnig hugo serve -D from inventory on error occur.

### ISSUE THREAD

**Issue by yokwejuste** [unicef/inventory#129]
# Summary

On following up [Step 2 issue](https://github.com/unicef/inventory-hugo-theme/issues/60) for Outreachy interns for this cohort, I got some challenges and difficulties. At the level of the [cohorts.html](https://github.com/unicef/inventory/blob/main/layouts/partials/cohorts.html), there was a problem at the level of  [line 110](https://github.com/unicef/inventory/blob/main/layouts/partials/cohorts.html#L110).

## What you expected to happen
I actually expected this, as seen in the picture below.
![img](https://user-images.githubusercontent.com/71908316/161040506-064001ad-2b19-4ea3-a30b-f04b3e1ffcf1.png)
That will be the correct output.

## What actually happened
A description for this is the picture below.
![img](https://user-images.githubusercontent.com/71908316/161040666-cc9212b9-708b-4aee-a02a-db94966da1e2.png)

## Suggestion
I have a solution which will be appropriate for this error.

**Comment by yokwejuste** [comment]
My Hugo version is 
![Screenshot from 2022-03-31 14-33-39](https://user-images.githubusercontent.com/71908316/161067199-6a2f16f9-938a-4919-9799-7525c3580cc5.png)
And from the Hugo released website, I got this info
![image](https://user-images.githubusercontent.com/71908316/161067418-7ca8520e-112b-48d5-8598-fde49f92daab.png)

**Comment by jwflory** [comment]
@yokwejuste Could you try upgrading to a newer version of Hugo and retest? I am not getting this issue. It could be because the Ubuntu repositories ship an outdated binary for Hugo.

Hugo releases notes are [no longer published](https://gohugo.io/news/no-more-releasenotes-here/) on the website, but you can find [new releases on GitHub](https://github.com/gohugoio/hugo/releases). The current version is v0.96.0. Try using the [binary cross-platform installation method](https://gohugo.io/getting-started/installing/#binary-cross-platform).
