### ISSUE TITLE
[HUGO] Add OpenGraph image and article metadata to articles / pages

### ISSUE THREAD

**Issue by jwflory** [unicef/inventory#18]
# Summary

When a hyperlink is shared from this website on a social media application, it should pull OpenGraph image and article metadata into the preview box.

# Background

**Is your feature request related to a problem? Please describe**:

When I share a link from the UNICEF O.S. Inventory site, the preview box only shows the article/page title. It is not engaging and not descriptive of the content on the page.

**Describe the solution you'd like**:

The social media "preview box" should show an OpenGraph image (e.g. site logo), a page title, the site title, and an article/page description if it exists.

**Describe alternatives you've considered**:

Do nothing. Does not mitigate user engagement concern, i.e. by better describing the page content, an interested reader is more likely to discover this content.

# Details

Some metadata _must_ be defined in the article/post front-matter:

* Article/post description
* Title (already required)
* Keywords

A **image** or logo could be optionally defined, but it should fall back on some kind of site-wide logo if a specific post does not define a custom image or logo.

# Outcome

Better promotion and visibility into the content and knowledge published on this site, before clicking the link to figure out what is hosted in UNICEF O.S. Inventory

**Comment by MuluhGodson** [comment]
# Summary
Support for MetaTags (Open Graph, Twitter Cards)


**Describe the solution you'd like**:
@jwflory My solution for this issue is to use Hugo template syntax and Front Matter, both of which are already being utilized. 
Hugo out of the box provides support for Meta tags (Open graphs and Twitter cards). 
How ever, solving this will involve including these templates in the themes submodule which I have created a PR [https://github.com/themefisher/dot-hugo-documentation-theme/pull/163](url) here for.


# Details

1. In the submodule themes/inventory open the partials folder and edit the head.html file.
Originally it looks like this:
```
<head>
  <meta charset="utf-8">
  <title>{{ .Title }}</title>

  {{ hugo.Generator }}

  {{ "<!-- mobile responsive meta -->" | safeHTML }}
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

  {{ "<!-- ** Plugins Needed for the Project ** -->" | safeHTML }}
  ...
```

2. After the `{{ hugo.Generator }}` line, which is the fourth line, add the following lines:
```
  {{ template "_internal/opengraph.html" . }}
  {{ template "_internal/twitter_cards.html" . }}
```
This should get it to look like this:
```
<head>
  <meta charset="utf-8">
  <title>{{ .Title }}</title>

  {{ hugo.Generator }}
  {{ template "_internal/opengraph.html" . }}
  {{ template "_internal/twitter_cards.html" . }}

  {{ "<!-- mobile responsive meta -->" | safeHTML }}
  <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
```
3. The setup is complete. Now what is left is that for each article or blog post or file that needs MetaTags, we use Front Matter keywords which is automatically interpreted by Hugo following the templates we included above. 
The front matter below generates the image shown in the outcome below:
```
---
title: "GPLv2 vs. GPLv3"
description: "This deals with opengl stuff"
images:
- https://www.opengl.org/img/opengl_logo.png
tags: ["gpl2", "gpl3", "unicef"]

---
```
4. Other keywords which are self-explanatory include:
- series: [ ]
- videos: [ ]

5. A general fallback image and/or description can be displayed as the generated thumbnail for the Opengraph which is set in the `config.toml` file as:
```
[params]
  description = "some cool text to describe this website in case the blog or article has no description included in its Front Matter"
  images = ["unicef-site-logo.jpg?"]
  title = "UNICEF O.S. Inventory"
```

# Outcome
The result of 3 above gives something like this: (tested locally with opengraph preview addons).
![opengraph](https://user-images.githubusercontent.com/40151808/116456939-0e768400-a820-11eb-802b-1e0926308447.png)

**Comment by jwflory** [comment]
Hi @MuluhGodson, thank you for your work on this!

> _**@MuluhGodson wrote…**_
>  How ever, solving this will involve including these templates in the themes submodule which I have created a PR [Pull Request Here](https://github.com/themefisher/dot-hugo-documentation-theme/pull/163) here for.

I see you sent the Pull Request upstream in themefisher/dot-hugo-documentation-theme#163. Let us see if upstream (a la @somratpro) is willing to accept your patch. Do note that your Pull Request used an out-of-date clone of the upstream `master` branch and you have merge conflicts to solve there.

> _**@MuluhGodson wrote…**_
> Since this repo still uses the submodule from the original repo, i created the PR there.
> To change this to use the forked repo, open the `.gitmodules` file in a text editor and change the url param to that of the forked repo.

It was actually an accident that I was still using the upstream repo. I updated that in PR #21. But it is actually a good idea to send a patch this small upstream first to see if they will take it for all users. I can integrate the patch in my downstream fork if upstream accepts it.

Also, tested this out on my side and it works great! Very cool to see this implemented.

![Screenshot of the OpenGraph preview of an example page in the website](https://user-images.githubusercontent.com/4721034/116477051-16e3b480-a84a-11eb-9e1c-8507b2e8baef.png "Screenshot of the OpenGraph preview of an example page in the website")

**Comment by jwflory** [comment]
Thanks again @MuluhGodson for working on this!
